"""Test migrate

Revision ID: b6ebbdb793f9
Revises: 
Create Date: 2025-12-17 09:27:25.872654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6ebbdb793f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_case_person', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_t_case_person_case_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_case_person', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_t_case_person_case_id'), ['case_id'], unique=False)

    # ### end Alembic commands ###
