"""empty message

Revision ID: da42841a9334
Revises: b6ebbdb793f9
Create Date: 2025-12-17 10:07:33.752497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da42841a9334'
down_revision = 'b6ebbdb793f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_case', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('t_case_jenis_karyawan_terlapor_id_fkey'), type_='foreignkey')
        batch_op.drop_column('jenis_karyawan_terlapor_id')

    with op.batch_alter_table('t_case_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_gm_hcca', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('approval_gm_fad', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('t_case_person', schema=None) as batch_op:
        batch_op.drop_column('approval_gm_fad')
        batch_op.drop_column('approval_gm_hcca')

    with op.batch_alter_table('t_case', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jenis_karyawan_terlapor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('t_case_jenis_karyawan_terlapor_id_fkey'), 'm_jenis_karyawan_terlapor', ['jenis_karyawan_terlapor_id'], ['id'])

    # ### end Alembic commands ###
